/**
 * This class is generated by jOOQ
 */
package me.signatured.vpnguarddatabase.vpnguard;


import javax.annotation.Generated;

import me.signatured.vpnguarddatabase.vpnguard.tables.CachedIp;


/**
 * Convenience access to all tables in vpnguard
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>vpnguard.cached_ip</code>.
     */
    public static final CachedIp CACHED_IP = me.signatured.vpnguarddatabase.vpnguard.tables.CachedIp.CACHED_IP;
}
