/**
 * This class is generated by jOOQ
 */
package me.signatured.vpnguarddatabase.vpnguard;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.signatured.vpnguarddatabase.DefaultCatalog;
import me.signatured.vpnguarddatabase.vpnguard.tables.CachedIp;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vpnguard extends SchemaImpl {

    private static final long serialVersionUID = -2097930806;

    /**
     * The reference instance of <code>vpnguard</code>
     */
    public static final Vpnguard VPNGUARD = new Vpnguard();

    /**
     * The table <code>vpnguard.cached_ip</code>.
     */
    public final CachedIp CACHED_IP = me.signatured.vpnguarddatabase.vpnguard.tables.CachedIp.CACHED_IP;

    /**
     * No further instances allowed
     */
    private Vpnguard() {
        super("vpnguard", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            CachedIp.CACHED_IP);
    }
}
